### PR TITLE
Catch the manifest exception as warning

### LINKED ISSUE #109: CommandError: Command exited with non-zero status code (1): time="2020-01-20T07:42:37Z" level=fatal msg="Error ...
Sentry Issue: [THOTH-1NC5](https://sentry.io/organizations/thoth-station/issues/1452461142/?referrer=github_integration)

```
CommandError: Command exited with non-zero status code (1): time="2020-01-20T07:42:37Z" level=fatal msg="Error determining manifest MIME type for docker://docker-registry.default.svc:5000/dh-prod-jupyterhub/cuda@sha256:1c637eb14e84957f263266c5de31b98e564586c719f8cfefec81dbd5489f64b9: Error reading manifest sha256:1c637eb14e84957f263266c5de31b98e564586c719f8cfefec81dbd5489f64b9 in docker-registry.default.svc:5000/dh-prod-jupyterhub/cuda: manifest unknown: manifest unknown" 

  File "app.py", line 320, in _submitter
    dst_verify_tls=not no_dst_registry_tls_verify,
  File "app.py", line 192, in _do_analyze_build
    dst_verify_tls=dst_verify_tls,
  File "app.py", line 278, in _push_image
    command = run_command(cmd)
  File "/opt/app-root/lib/python3.6/site-packages/thoth/analyzer/command.py", line 107, in run_command
    raise CommandError(error_msg, command=command, is_json=is_json)

Failed to submit image "docker-registry.default.svc:5000/dh-prod-jupyterhub/cuda:10.0-cudnn7-runtime-ubi7" for analysis to Thoth: Command exited with non-zero status code (1): time="2020-01-20T07:42:37Z" level=fatal msg="Error determining manifest MIME type for docker://docker-registry.default.svc:5000/dh-prod-jupyterhub/cuda@sha256:1c637eb14e84957f263266c5de31b98e564586c719f8cfefec81dbd5489f64b9: Error reading manifest sha256:1c637eb14e84957f263266c5de31b98e564586c719f8cfefec81dbd5489f64b9 in docker-registry.default.svc:5000/dh-prod-jupyterhub/cuda: manifest unknown: manifest unknown" 

```

### PR DESCRIPTION
**Pull request by harshad16**
Catch the manifest exception as a warning

Discussion: #109
Fixes: #109 #115 #111 

Alternative methods tried: Checking if the base image is present in image stream, causes the loss of few more images, as they are present in the registry but not on image stream.
Maybe one of the preemptive we can take is to catch the manifest issue as a warning.

Signed-off-by: Harshad Reddy Nalla <hnalla@redhat.com>

### CODE REVIEW

**Review by fridex — COMMENTED** [review]
This will catch any exception happened during pushing images - do we want that? We will lose all the other errors as they will not be reported at all.

**Comment by fridex** [comment]
> This will catch any exception happened during pushing images - do we want that? We will lose all the other errors as they will not be reported at all.

what about something like this?

```python
try:
   # push logic
except CommandErrr as exc:
    if "Error determining manifest MIME type" in exc.stderr:
        # ... why we don't want this:
        _LOGGER.warning("Ignoring error caused by invalid manifest MIME type during push: %s", str(exc))
    else:
        raise

**Comment by harshad16** [comment]
@fridex thanks for the comments and tips. 

Reference to older similar issues:
https://github.com/thoth-station/analyzer/issues/48
https://github.com/thoth-station/analyzer/issues/48#issuecomment-429349401

**Review by fridex — APPROVED** [review]
LGTM, thanks! :100: :+1:

**Pull request merged**
