### PR TITLE
setup probe on dc as it uses events

### PR DESCRIPTION
**Pull request by harshad16**
setup probe on dc as it uses OpenShift events
Signed-off-by: Harshad Reddy Nalla <hnalla@redhat.com>

### CODE REVIEW

**Review by fridex — COMMENTED** [review]
What about making it directly part of dc?

**Comment by fridex** [comment]
BTW I wonder if the issue is still present, we have updated kubernetes/openshift client libraries. We could give it a try.

**Review by fridex — APPROVED** [review]
thanks! :1st_place_medal: :+1:

**Comment by harshad16** [comment]
> What about making it directly part of dc?

Ah, right i updated the deployment config with livenessProbe.

> BTW I wonder if the issue is still present, we have updated kubernetes/openshift client libraries. We could give it a try.

sure, let not merge the pr, and see what happens in the build-watcher instance deployed in jupyterhub and thoth-test-core.

**Comment by harshad16** [comment]
> thanks!

ah, i will try to track the already deployed modules, if they show events not picking issue, i will update the deployment. :+1:

**Comment by fridex** [comment]
> > thanks!
> 
> ah, i will try to track the already deployed modules, if they show events not picking issue, i will update the deployment.

:1st_place_medal: :+1:

**Pull request merged**
