### PR TITLE
fixed the webhook url of the build trigger job

### PR DESCRIPTION
**Pull request by goern**
Signed-off-by: Christoph Görn <goern@redhat.com>

### CODE REVIEW

**Review by harshad16 — APPROVED** [review]

**Comment by harshad16** [comment]
@goern should we remove the queue from workload-operator as well, so that thoth-zuul take care of PR in that repo as well.

**Comment by goern** [comment]
its not a matter of the queue, more like the prerequisites for zuul to merge are not fulfilled, see https://github.com/thoth-station/zuul-config/blob/master/zuul.d/_pipelines.yaml#L46-L56

**Comment by goern** [comment]
regate

**Comment by goern** [comment]
regate

**Comment by goern** [comment]
Zuul was confused by the required WIP check, I turned it into 'not required'

**Pull request merged**
